substitutions:
  bright_level: "31"
  dark_level: "20"
  dark_mode_sprays: "2"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"

esphome:
  name: freshmatic-bathroom
  friendly_name: Freshmatic Bathroom

esp8266:
  board: d1_mini
  restore_from_flash: true

<<: !include .e_base.yaml

globals:
  - id: sprays
    type: float
    restore_value: yes

logger:
  logs:
    adc: none
    sensor: none
    light: none
    select: none

binary_sensor:
  - platform: gpio
    id: reset
    pin: D4
    filters:
      - invert:
    on_click:
      min_length: 500ms
      max_length: 5000ms
      then:
        - light.turn_on:
            id: led
            effect: flashfast
        - lambda: |-
            id(sprays) = 0;

button:
  - platform: template
    name: Reset
    id: reset_button
    on_press:
      - lambda: |-
          id(sprays) = 0;
      - lambda: |-
          global_preferences->sync();

select:
  - platform: template
    name: Interval
    id: set_interval
    icon: mdi:timer-outline
    optimistic: true
    restore_value: true
    options:
      - 0 (Bathroom Mode)
      - $interval1 Minutes
      - $interval2 Minutes
      - $interval3 Minutes
      - $interval4 Minutes
      - $interval5 Minutes
    on_value:
      - if:
          condition:
            - switch.is_on: enable
            - lambda: "return atoi(x.c_str()) >= 1;"
          then:
            - switch.turn_on: spray

sensor:
  - platform: template
    name: Can
    id: can_level
    device_class: pressure
    unit_of_measurement: "Can"
    update_interval: 2s
    lambda: |-
      return ((2500 - id(sprays)) / 2500) * 100;

  - platform: adc
    name: Lux
    id: brightness
    device_class: illuminance
    unit_of_measurement: lx
    pin: A0
    update_interval: 1s
    filters:
      - lambda: return 85 - (x * 150);
      - sliding_window_moving_average:
          window_size: 3
          send_every: 3
    on_value:
      - if:
          condition:
            for:
              time: 20min
              condition:
                and:
                  - switch.is_on: enable
                  - lambda: "return atoi(id(set_interval).current_option()) == 0;"
                  - lambda: "return id(brightness).state < $dark_level;"
                  - switch.is_off: its_dark
          then:
            - switch.turn_on: its_dark
      - if:
          condition:
            and:
              - switch.is_on: enable
              - lambda: "return atoi(id(set_interval).current_option()) == 0;"
              - lambda: "return id(brightness).state > $bright_level;"
              - switch.is_on: its_dark
          then:
            - switch.turn_on: spray
            - delay: !lambda return (1500 * $dark_mode_sprays);
            - switch.turn_off: its_dark

switch:
  - platform: gpio
    name: Spray
    id: spray
    icon: mdi:spray
    pin: D2
    on_turn_on:
      - light.turn_on:
          id: led
          effect: pulser
      - switch.turn_on: timer
      - delay: 0.2s
      - switch.turn_off: spray
      - lambda: |-
          id(sprays) += 1;

  - platform: template
    name: Enable
    id: enable
    icon: mdi:autorenew
    optimistic: true
    on_turn_on:
      - switch.turn_on: timer

  - platform: template
    name: is Dark
    id: its_dark
    icon: mdi:brightness-4
    optimistic: true

  - platform: template
    id: timer
    optimistic: true
    on_turn_on:
      - delay: !lambda return atoi(id(set_interval).current_option()) * 60000;
      - switch.turn_off: timer
      - if:
          condition:
            - switch.is_on: enable
            - lambda: "return atoi(id(set_interval).current_option()) >= 1;"
          then:
            - light.turn_on:
                id: led
                effect: flashfast
            - delay: 1.0s
            - light.turn_off: led
            - switch.turn_on: spray

light:
  - platform: monochromatic
    name: LED
    id: led
    output: out_led
    default_transition_length: 0s
    effects:
      - pulse:
          name: pulser
          transition_length: 0.0s
          update_interval: 0.25s
      - pulse:
          name: flashfast
          transition_length: 0.0s
          update_interval: 0.025s
    on_turn_on:
      - delay: 3s
      - light.turn_off: led

output:
  - platform: esp8266_pwm
    pin:
      number: D3
      inverted: true
    id: out_led
